#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def lonelyinteger(a):
    # Write your code here
    no_dict = {}
    for i in a:
        if  i in no_dict:
            no_dict[i] += 1
        else:
            no_dict[i] = 1
    for i,j in no_dict.items():
        if j ==1:
            return i
# lonelyinteger([1,2,3,4,1,2,3])

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
