#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here

    sortedarr = sorted(arr)
    maxedsum = sortedarr[1:]    
    minsum =   sortedarr[:-1]
   
    print(sum(minsum),sum(maxedsum))
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
