#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#
no_positives= 0
no_negatives=0
no_zero = 0
def plusMinus(arr):
    # Write your code here
    global no_positives
    global no_negatives
    global no_zero
    for i in arr:
        if i >0:
            no_positives +=1
        elif i < 0:
            no_negatives +=1
        else:
            no_zero +=1
    print("{:.5f}\n{:.5f}\n{:.5f}".format(no_positives/len(arr),no_negatives/len(arr),no_zero/len(arr)) )
  
            

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
